# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf8cfeb19347c58431f5b36af7b3fefe642e28c4536b808934a918069ae73a702eebd0a6e138bcb070571b29a3feaaf4f5999a53abb125dd55c15cc23af7f8ce

test:
  secret_key_base: 393486e9dc7c9260f41fecd86704297778335f492de92fd6d5f2efb37a8ef2ad6929bd24cc731303cdfde0eaa4901a87deb7547f8bf35b0c75eb335217ed5ad5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
